optuna:
  direction: "maximize"
  n_trials: 30
  timeout: 600
  seed: 42

search_space:
  scale_mu: [0.5, 4.0]
  persistence: [2, 15]
  slippage: [0.00005, 0.001]
  commission: [0.00005, 0.001]
  max_drawdown: [0.05, 0.25]
  long_only: [true, false]
  vol_weight: [true, false]
