general:
  seed: 42

data:
  ticker: "QQQQ"
  start_date: "2012-01-01"
  save_path: "data/qqq.csv"

simulation:
  n_paths: 5000
  n_steps: 252
  start_state: "Neutral"
  S0: 100

regimes:
  scale_mu: 2.5
  auto_estimate: true

trading:
  slippage: 0.0001
  commission: 0.0001
  max_drawdown: 0.2
  persistence: 8
  long_only: true
  vol_weight: false

performance:
  plot_sharpe_hist: true
  plot_equity_curves: false
  output_csv: "results/performance_summary.csv"
