# ==================================================
#  Markov Monte Carlo Trading Simulator Parameters
# ==================================================

# Data Settings
data:
  ticker: "QQQ"
  start_date: "2012-01-01"
  save_path: "../data/iwm.csv"

# Simulation Settings
simulation:
  n_paths: 5000           
  n_steps: 252            
  start_state: "Neutral"  
  S0: 100                

# Regime Model Settings
regimes:
  scale_mu: 2.0           
  auto_estimate: true

# Policy Settings
trading:
  slippage: 0.0001
  commission: 0.00001
  max_drawdown: 0.1
  persistence: 8
  long_only: true
  vol_weight: true

# Performance Settings
performance:
  plot_sharpe_hist: true
  plot_equity_curves: false
  output_csv: "results/performance_summary.csv"
