# ==================================================
#  Markov Monte Carlo Trading Simulator Parameters
# ==================================================

# Data Settings
data:
  ticker: "QQQ"
  start_date: "2018-01-01"
  save_path: "../data/qqq.csv"

# Simulation Settings
simulation:
  n_paths: 2000           
  n_steps: 252            
  start_state: "Neutral"  
  S0: 100                

# Regime Model Settings
regimes:
  scale_mu: 1.5           
  auto_estimate: true

# Policy Settings
trading:
  slippage: 0.0002
  commission: 0.0001
  max_drawdown: 0.15
  persistence: 3
  long_only: false
  vol_weight: true

# Performance Settings
performance:
  plot_sharpe_hist: true
  plot_equity_curves: false
  output_csv: "results/performance_summary.csv"
